import type { Board, Task } from "./types"

export const mockBoards: Board[] = [
  {
    id: "1",
    name: "Product Development",
    description: "Track all product features and improvements",
    owner: "0x1234...5678",
    members: ["0x1234...5678", "0xabcd...efgh"],
    taskIds: ["1", "2", "3"],
    createdAt: Date.now() - 86400000 * 7,
    columns: [
      { id: "todo", name: "To Do", order: 0, color: "#94a3b8" },
      { id: "in_progress", name: "In Progress", order: 1, color: "#3b82f6" },
      { id: "review", name: "Review", order: 2, color: "#f59e0b" },
      { id: "done", name: "Done", order: 3, color: "#10b981" },
    ],
  },
  {
    id: "2",
    name: "Marketing Campaign",
    description: "Q1 2025 marketing initiatives",
    owner: "0x1234...5678",
    members: ["0x1234...5678"],
    taskIds: ["4", "5"],
    createdAt: Date.now() - 86400000 * 3,
    columns: [
      { id: "backlog", name: "Backlog", order: 0, color: "#64748b" },
      { id: "in_progress", name: "In Progress", order: 1, color: "#3b82f6" },
      { id: "done", name: "Done", order: 2, color: "#10b981" },
    ],
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    boardId: "1",
    title: "Design new landing page",
    description: "Create mockups for the updated homepage",
    status: "in_progress",
    assignee: "0x1234...5678",
    creator: "0x1234...5678",
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
    storyPoints: 5,
    priority: "high",
  },
  {
    id: "2",
    boardId: "1",
    title: "Implement wallet integration",
    description: "Add Sui wallet connect functionality",
    status: "todo",
    assignee: null,
    creator: "0x1234...5678",
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
    storyPoints: 8,
    priority: "urgent",
  },
  {
    id: "3",
    boardId: "1",
    title: "Write documentation",
    description: "Complete user guide and API docs",
    status: "done",
    assignee: "0xabcd...efgh",
    creator: "0x1234...5678",
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 2,
    storyPoints: 3,
    priority: "medium",
  },
  {
    id: "4",
    boardId: "2",
    title: "Launch social media campaign",
    description: "Coordinate posts across all platforms",
    status: "in_progress",
    assignee: "0x1234...5678",
    creator: "0x1234...5678",
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 3600000,
    storyPoints: 5,
    priority: "high",
  },
  {
    id: "5",
    boardId: "2",
    title: "Design email templates",
    description: "Create responsive email designs",
    status: "backlog",
    assignee: null,
    creator: "0x1234...5678",
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
    storyPoints: 3,
    priority: "low",
  },
]
